### ISSUE TITLE
enable github actions?

### ISSUE THREAD

**Issue by mathause** [romatt/exseas_explorer#19]
I'd still be interested to write some tests for this. @romatt can you enable github actions (or make me an admin for the repo).

**Comment by romatt** [comment]
Hmm I can only remove you but not grant any admin permissions:
![image](https://user-images.githubusercontent.com/77632960/196792431-ae5e5d09-557c-4723-87fd-a24af8a015b0.png)
Am I doing it wrong? I'm much more used to GitLab then GitHub...

**Comment by mathause** [comment]
It seems there is no way to change my permissions for a private repo. But maybe I can enable the actions by myself. I can give it a try. Otherwise we'd have to move it to an organization.
