### ISSUE TITLE
download still not working?

### ISSUE THREAD

**Issue by mathause** [romatt/exseas_explorer#32]
I can't get the download to work. What browser did you test this in? It could be related to using a `form` that may not send the correct headers?

**Comment by mathause** [comment]
The download in #29 did not work for me locally, complaining about a path-not-found. Therefore, I implemented #31 (which does not work either). I am happy to revert #31 and test it again.

**Comment by romatt** [comment]
Hmm, is your data in a different location relative to the app then?

**Comment by mathause** [comment]
I don't think so. I'll merge #35 and test it again...

**Comment by mathause** [comment]
I just tried it out and realized that the path has to be changed here:

https://github.com/romatt/exseas_explorer/blob/85e035959a2fa1bc5cbd000bc88136f7d5891546/exseas_explorer/app.py#L693

Happy to do this (but that would leave the problem with creating a ton on json files.)

**Comment by mathause** [comment]
Maybe we can use `flask.send_file`, like so or similar:

```python
import io

flask.send_file(
    io.StringIO(gdf.to_json()),
    mimetype='application/json',
    as_attachment=True,
    download_name=f"tmp_{uuid.uuid1()}.geojson"
)
```
