### ISSUE TITLE
font weight

### ISSUE THREAD

**Issue by mathause** [romatt/exseas_explorer#37]
I find the text quite difficult to read https://intexseas-explorer.ethz.ch/ and I think it's due to the font weight. Do you want to keep it as is or can I set it to "normal"?

https://github.com/romatt/exseas_explorer/blob/62528f5f854d77a535bd085164cadcf8e40a076c/exseas_explorer/assets/style.css#L4

**Comment by romatt** [comment]
Oh sure, change it back to normal that change was not intentional!
